spring:
  data:
    mongodb:
        uri: mongodb://localhost:27017/neighbours-socializer
        auto-index-creation: true

keycloak:
  realm: we-are-locals
  auth-server-url: http://localhost:8090
  resource: we-are-locals-backend
